/********************************************************************************
** Form generated from reading UI file 'keyboard.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_KEYBOARD_H
#define UI_KEYBOARD_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_KeyBoard
{
public:
    QWidget *widget;
    QPushButton *pushButton_shangjuhao;
    QPushButton *num_7_Bt;
    QPushButton *a_Bt;
    QPushButton *delBt;
    QPushButton *g_Bt;
    QPushButton *pushButton_liangpie;
    QPushButton *x_Bt;
    QPushButton *num_5_Bt;
    QPushButton *k_Bt;
    QPushButton *caps_Bt;
    QPushButton *w_Bt;
    QPushButton *prevBt;
    QPushButton *spaceBt;
    QPushButton *nextBt;
    QPushButton *num_6_Bt;
    QPushButton *o_Bt;
    QPushButton *num_1_Bt;
    QPushButton *zh_10_Bt;
    QPushButton *pushButton_danshu;
    QPushButton *zh_us_Bt;
    QPushButton *zh_3_Bt;
    QPushButton *q_Bt;
    QPushButton *n_Bt;
    QPushButton *y_Bt;
    QPushButton *h_Bt;
    QLabel *langLb;
    QPushButton *d_Bt;
    QPushButton *r_Bt;
    QPushButton *num_0_Bt;
    QPushButton *num_2_Bt;
    QPushButton *u_Bt;
    QPushButton *zh_7_Bt;
    QPushButton *zh_1_Bt;
    QPushButton *zh_9_Bt;
    QPushButton *s_Bt;
    QPushButton *e_Bt;
    QPushButton *j_Bt;
    QLabel *showLb;
    QPushButton *num_3_Bt;
    QPushButton *b_Bt;
    QPushButton *pushButton_pie;
    QPushButton *z_Bt;
    QPushButton *zh_5_Bt;
    QPushButton *v_Bt;
    QPushButton *num_9_Bt;
    QPushButton *l_Bt;
    QPushButton *zh_8_Bt;
    QPushButton *zh_2_Bt;
    QPushButton *closeBt;
    QPushButton *num_4_Bt;
    QPushButton *t_Bt;
    QPushButton *f_Bt;
    QPushButton *m_Bt;
    QPushButton *i_Bt;
    QPushButton *zh_6_Bt;
    QPushButton *p_Bt;
    QPushButton *num_8_Bt;
    QPushButton *c_Bt;
    QPushButton *zh_4_Bt;

    void setupUi(QDialog *KeyBoard)
    {
        if (KeyBoard->objectName().isEmpty())
            KeyBoard->setObjectName(QString::fromUtf8("KeyBoard"));
        KeyBoard->setEnabled(true);
        KeyBoard->resize(800, 240);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(KeyBoard->sizePolicy().hasHeightForWidth());
        KeyBoard->setSizePolicy(sizePolicy);
        KeyBoard->setMinimumSize(QSize(0, 0));
        KeyBoard->setMaximumSize(QSize(1000, 1000));
        KeyBoard->setStyleSheet(QString::fromUtf8(""));
        widget = new QWidget(KeyBoard);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(0, 0, 800, 240));
        pushButton_shangjuhao = new QPushButton(widget);
        pushButton_shangjuhao->setObjectName(QString::fromUtf8("pushButton_shangjuhao"));
        pushButton_shangjuhao->setGeometry(QRect(550, 10, 51, 36));
        num_7_Bt = new QPushButton(widget);
        num_7_Bt->setObjectName(QString::fromUtf8("num_7_Bt"));
        num_7_Bt->setGeometry(QRect(610, 100, 51, 36));
        QSizePolicy sizePolicy1(QSizePolicy::Minimum, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(num_7_Bt->sizePolicy().hasHeightForWidth());
        num_7_Bt->setSizePolicy(sizePolicy1);
        a_Bt = new QPushButton(widget);
        a_Bt->setObjectName(QString::fromUtf8("a_Bt"));
        a_Bt->setGeometry(QRect(70, 146, 51, 36));
        sizePolicy1.setHeightForWidth(a_Bt->sizePolicy().hasHeightForWidth());
        a_Bt->setSizePolicy(sizePolicy1);
        delBt = new QPushButton(widget);
        delBt->setObjectName(QString::fromUtf8("delBt"));
        delBt->setGeometry(QRect(670, 11, 51, 36));
        sizePolicy1.setHeightForWidth(delBt->sizePolicy().hasHeightForWidth());
        delBt->setSizePolicy(sizePolicy1);
        g_Bt = new QPushButton(widget);
        g_Bt->setObjectName(QString::fromUtf8("g_Bt"));
        g_Bt->setGeometry(QRect(310, 146, 51, 36));
        sizePolicy1.setHeightForWidth(g_Bt->sizePolicy().hasHeightForWidth());
        g_Bt->setSizePolicy(sizePolicy1);
        pushButton_liangpie = new QPushButton(widget);
        pushButton_liangpie->setObjectName(QString::fromUtf8("pushButton_liangpie"));
        pushButton_liangpie->setGeometry(QRect(670, 56, 51, 36));
        x_Bt = new QPushButton(widget);
        x_Bt->setObjectName(QString::fromUtf8("x_Bt"));
        x_Bt->setGeometry(QRect(130, 191, 51, 36));
        sizePolicy1.setHeightForWidth(x_Bt->sizePolicy().hasHeightForWidth());
        x_Bt->setSizePolicy(sizePolicy1);
        num_5_Bt = new QPushButton(widget);
        num_5_Bt->setObjectName(QString::fromUtf8("num_5_Bt"));
        num_5_Bt->setGeometry(QRect(670, 146, 51, 36));
        sizePolicy1.setHeightForWidth(num_5_Bt->sizePolicy().hasHeightForWidth());
        num_5_Bt->setSizePolicy(sizePolicy1);
        k_Bt = new QPushButton(widget);
        k_Bt->setObjectName(QString::fromUtf8("k_Bt"));
        k_Bt->setGeometry(QRect(490, 146, 51, 36));
        sizePolicy1.setHeightForWidth(k_Bt->sizePolicy().hasHeightForWidth());
        k_Bt->setSizePolicy(sizePolicy1);
        caps_Bt = new QPushButton(widget);
        caps_Bt->setObjectName(QString::fromUtf8("caps_Bt"));
        caps_Bt->setGeometry(QRect(11, 146, 51, 36));
        sizePolicy1.setHeightForWidth(caps_Bt->sizePolicy().hasHeightForWidth());
        caps_Bt->setSizePolicy(sizePolicy1);
        w_Bt = new QPushButton(widget);
        w_Bt->setObjectName(QString::fromUtf8("w_Bt"));
        w_Bt->setGeometry(QRect(70, 101, 51, 36));
        sizePolicy1.setHeightForWidth(w_Bt->sizePolicy().hasHeightForWidth());
        w_Bt->setSizePolicy(sizePolicy1);
        prevBt = new QPushButton(widget);
        prevBt->setObjectName(QString::fromUtf8("prevBt"));
        prevBt->setGeometry(QRect(410, 10, 61, 36));
        sizePolicy1.setHeightForWidth(prevBt->sizePolicy().hasHeightForWidth());
        prevBt->setSizePolicy(sizePolicy1);
        spaceBt = new QPushButton(widget);
        spaceBt->setObjectName(QString::fromUtf8("spaceBt"));
        spaceBt->setGeometry(QRect(489, 191, 111, 36));
        sizePolicy1.setHeightForWidth(spaceBt->sizePolicy().hasHeightForWidth());
        spaceBt->setSizePolicy(sizePolicy1);
        nextBt = new QPushButton(widget);
        nextBt->setObjectName(QString::fromUtf8("nextBt"));
        nextBt->setGeometry(QRect(480, 10, 61, 36));
        sizePolicy1.setHeightForWidth(nextBt->sizePolicy().hasHeightForWidth());
        nextBt->setSizePolicy(sizePolicy1);
        num_6_Bt = new QPushButton(widget);
        num_6_Bt->setObjectName(QString::fromUtf8("num_6_Bt"));
        num_6_Bt->setGeometry(QRect(730, 146, 51, 36));
        sizePolicy1.setHeightForWidth(num_6_Bt->sizePolicy().hasHeightForWidth());
        num_6_Bt->setSizePolicy(sizePolicy1);
        o_Bt = new QPushButton(widget);
        o_Bt->setObjectName(QString::fromUtf8("o_Bt"));
        o_Bt->setGeometry(QRect(490, 101, 51, 36));
        sizePolicy1.setHeightForWidth(o_Bt->sizePolicy().hasHeightForWidth());
        o_Bt->setSizePolicy(sizePolicy1);
        num_1_Bt = new QPushButton(widget);
        num_1_Bt->setObjectName(QString::fromUtf8("num_1_Bt"));
        num_1_Bt->setGeometry(QRect(610, 191, 51, 36));
        sizePolicy1.setHeightForWidth(num_1_Bt->sizePolicy().hasHeightForWidth());
        num_1_Bt->setSizePolicy(sizePolicy1);
        zh_10_Bt = new QPushButton(widget);
        zh_10_Bt->setObjectName(QString::fromUtf8("zh_10_Bt"));
        zh_10_Bt->setGeometry(QRect(550, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_10_Bt->sizePolicy().hasHeightForWidth());
        zh_10_Bt->setSizePolicy(sizePolicy1);
        pushButton_danshu = new QPushButton(widget);
        pushButton_danshu->setObjectName(QString::fromUtf8("pushButton_danshu"));
        pushButton_danshu->setGeometry(QRect(610, 10, 51, 36));
        zh_us_Bt = new QPushButton(widget);
        zh_us_Bt->setObjectName(QString::fromUtf8("zh_us_Bt"));
        zh_us_Bt->setGeometry(QRect(10, 190, 51, 41));
        sizePolicy1.setHeightForWidth(zh_us_Bt->sizePolicy().hasHeightForWidth());
        zh_us_Bt->setSizePolicy(sizePolicy1);
        zh_3_Bt = new QPushButton(widget);
        zh_3_Bt->setObjectName(QString::fromUtf8("zh_3_Bt"));
        zh_3_Bt->setGeometry(QRect(130, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_3_Bt->sizePolicy().hasHeightForWidth());
        zh_3_Bt->setSizePolicy(sizePolicy1);
        q_Bt = new QPushButton(widget);
        q_Bt->setObjectName(QString::fromUtf8("q_Bt"));
        q_Bt->setGeometry(QRect(11, 101, 51, 36));
        sizePolicy1.setHeightForWidth(q_Bt->sizePolicy().hasHeightForWidth());
        q_Bt->setSizePolicy(sizePolicy1);
        n_Bt = new QPushButton(widget);
        n_Bt->setObjectName(QString::fromUtf8("n_Bt"));
        n_Bt->setGeometry(QRect(370, 191, 51, 36));
        sizePolicy1.setHeightForWidth(n_Bt->sizePolicy().hasHeightForWidth());
        n_Bt->setSizePolicy(sizePolicy1);
        y_Bt = new QPushButton(widget);
        y_Bt->setObjectName(QString::fromUtf8("y_Bt"));
        y_Bt->setGeometry(QRect(310, 101, 51, 36));
        sizePolicy1.setHeightForWidth(y_Bt->sizePolicy().hasHeightForWidth());
        y_Bt->setSizePolicy(sizePolicy1);
        h_Bt = new QPushButton(widget);
        h_Bt->setObjectName(QString::fromUtf8("h_Bt"));
        h_Bt->setGeometry(QRect(370, 146, 51, 36));
        sizePolicy1.setHeightForWidth(h_Bt->sizePolicy().hasHeightForWidth());
        h_Bt->setSizePolicy(sizePolicy1);
        langLb = new QLabel(widget);
        langLb->setObjectName(QString::fromUtf8("langLb"));
        langLb->setGeometry(QRect(11, 11, 44, 34));
        langLb->setAlignment(Qt::AlignCenter);
        d_Bt = new QPushButton(widget);
        d_Bt->setObjectName(QString::fromUtf8("d_Bt"));
        d_Bt->setGeometry(QRect(190, 146, 51, 36));
        sizePolicy1.setHeightForWidth(d_Bt->sizePolicy().hasHeightForWidth());
        d_Bt->setSizePolicy(sizePolicy1);
        r_Bt = new QPushButton(widget);
        r_Bt->setObjectName(QString::fromUtf8("r_Bt"));
        r_Bt->setGeometry(QRect(190, 101, 51, 36));
        sizePolicy1.setHeightForWidth(r_Bt->sizePolicy().hasHeightForWidth());
        r_Bt->setSizePolicy(sizePolicy1);
        num_0_Bt = new QPushButton(widget);
        num_0_Bt->setObjectName(QString::fromUtf8("num_0_Bt"));
        num_0_Bt->setGeometry(QRect(610, 56, 51, 36));
        sizePolicy1.setHeightForWidth(num_0_Bt->sizePolicy().hasHeightForWidth());
        num_0_Bt->setSizePolicy(sizePolicy1);
        num_2_Bt = new QPushButton(widget);
        num_2_Bt->setObjectName(QString::fromUtf8("num_2_Bt"));
        num_2_Bt->setGeometry(QRect(670, 190, 51, 36));
        sizePolicy1.setHeightForWidth(num_2_Bt->sizePolicy().hasHeightForWidth());
        num_2_Bt->setSizePolicy(sizePolicy1);
        u_Bt = new QPushButton(widget);
        u_Bt->setObjectName(QString::fromUtf8("u_Bt"));
        u_Bt->setGeometry(QRect(370, 101, 51, 36));
        sizePolicy1.setHeightForWidth(u_Bt->sizePolicy().hasHeightForWidth());
        u_Bt->setSizePolicy(sizePolicy1);
        zh_7_Bt = new QPushButton(widget);
        zh_7_Bt->setObjectName(QString::fromUtf8("zh_7_Bt"));
        zh_7_Bt->setGeometry(QRect(370, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_7_Bt->sizePolicy().hasHeightForWidth());
        zh_7_Bt->setSizePolicy(sizePolicy1);
        zh_1_Bt = new QPushButton(widget);
        zh_1_Bt->setObjectName(QString::fromUtf8("zh_1_Bt"));
        zh_1_Bt->setGeometry(QRect(11, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_1_Bt->sizePolicy().hasHeightForWidth());
        zh_1_Bt->setSizePolicy(sizePolicy1);
        zh_9_Bt = new QPushButton(widget);
        zh_9_Bt->setObjectName(QString::fromUtf8("zh_9_Bt"));
        zh_9_Bt->setGeometry(QRect(490, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_9_Bt->sizePolicy().hasHeightForWidth());
        zh_9_Bt->setSizePolicy(sizePolicy1);
        s_Bt = new QPushButton(widget);
        s_Bt->setObjectName(QString::fromUtf8("s_Bt"));
        s_Bt->setGeometry(QRect(130, 146, 51, 36));
        sizePolicy1.setHeightForWidth(s_Bt->sizePolicy().hasHeightForWidth());
        s_Bt->setSizePolicy(sizePolicy1);
        e_Bt = new QPushButton(widget);
        e_Bt->setObjectName(QString::fromUtf8("e_Bt"));
        e_Bt->setGeometry(QRect(130, 101, 51, 36));
        sizePolicy1.setHeightForWidth(e_Bt->sizePolicy().hasHeightForWidth());
        e_Bt->setSizePolicy(sizePolicy1);
        j_Bt = new QPushButton(widget);
        j_Bt->setObjectName(QString::fromUtf8("j_Bt"));
        j_Bt->setGeometry(QRect(430, 146, 51, 36));
        sizePolicy1.setHeightForWidth(j_Bt->sizePolicy().hasHeightForWidth());
        j_Bt->setSizePolicy(sizePolicy1);
        showLb = new QLabel(widget);
        showLb->setObjectName(QString::fromUtf8("showLb"));
        showLb->setGeometry(QRect(70, 11, 321, 31));
        showLb->setStyleSheet(QString::fromUtf8(""));
        showLb->setAlignment(Qt::AlignCenter);
        num_3_Bt = new QPushButton(widget);
        num_3_Bt->setObjectName(QString::fromUtf8("num_3_Bt"));
        num_3_Bt->setGeometry(QRect(730, 191, 51, 36));
        sizePolicy1.setHeightForWidth(num_3_Bt->sizePolicy().hasHeightForWidth());
        num_3_Bt->setSizePolicy(sizePolicy1);
        b_Bt = new QPushButton(widget);
        b_Bt->setObjectName(QString::fromUtf8("b_Bt"));
        b_Bt->setGeometry(QRect(310, 191, 51, 36));
        sizePolicy1.setHeightForWidth(b_Bt->sizePolicy().hasHeightForWidth());
        b_Bt->setSizePolicy(sizePolicy1);
        pushButton_pie = new QPushButton(widget);
        pushButton_pie->setObjectName(QString::fromUtf8("pushButton_pie"));
        pushButton_pie->setGeometry(QRect(730, 56, 51, 36));
        z_Bt = new QPushButton(widget);
        z_Bt->setObjectName(QString::fromUtf8("z_Bt"));
        z_Bt->setGeometry(QRect(70, 191, 51, 36));
        sizePolicy1.setHeightForWidth(z_Bt->sizePolicy().hasHeightForWidth());
        z_Bt->setSizePolicy(sizePolicy1);
        zh_5_Bt = new QPushButton(widget);
        zh_5_Bt->setObjectName(QString::fromUtf8("zh_5_Bt"));
        zh_5_Bt->setGeometry(QRect(250, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_5_Bt->sizePolicy().hasHeightForWidth());
        zh_5_Bt->setSizePolicy(sizePolicy1);
        v_Bt = new QPushButton(widget);
        v_Bt->setObjectName(QString::fromUtf8("v_Bt"));
        v_Bt->setGeometry(QRect(250, 191, 51, 36));
        sizePolicy1.setHeightForWidth(v_Bt->sizePolicy().hasHeightForWidth());
        v_Bt->setSizePolicy(sizePolicy1);
        num_9_Bt = new QPushButton(widget);
        num_9_Bt->setObjectName(QString::fromUtf8("num_9_Bt"));
        num_9_Bt->setGeometry(QRect(730, 100, 51, 36));
        sizePolicy1.setHeightForWidth(num_9_Bt->sizePolicy().hasHeightForWidth());
        num_9_Bt->setSizePolicy(sizePolicy1);
        l_Bt = new QPushButton(widget);
        l_Bt->setObjectName(QString::fromUtf8("l_Bt"));
        l_Bt->setGeometry(QRect(550, 146, 51, 36));
        sizePolicy1.setHeightForWidth(l_Bt->sizePolicy().hasHeightForWidth());
        l_Bt->setSizePolicy(sizePolicy1);
        zh_8_Bt = new QPushButton(widget);
        zh_8_Bt->setObjectName(QString::fromUtf8("zh_8_Bt"));
        zh_8_Bt->setGeometry(QRect(430, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_8_Bt->sizePolicy().hasHeightForWidth());
        zh_8_Bt->setSizePolicy(sizePolicy1);
        zh_2_Bt = new QPushButton(widget);
        zh_2_Bt->setObjectName(QString::fromUtf8("zh_2_Bt"));
        zh_2_Bt->setGeometry(QRect(70, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_2_Bt->sizePolicy().hasHeightForWidth());
        zh_2_Bt->setSizePolicy(sizePolicy1);
        closeBt = new QPushButton(widget);
        closeBt->setObjectName(QString::fromUtf8("closeBt"));
        closeBt->setGeometry(QRect(730, 10, 51, 36));
        sizePolicy1.setHeightForWidth(closeBt->sizePolicy().hasHeightForWidth());
        closeBt->setSizePolicy(sizePolicy1);
        num_4_Bt = new QPushButton(widget);
        num_4_Bt->setObjectName(QString::fromUtf8("num_4_Bt"));
        num_4_Bt->setGeometry(QRect(610, 146, 51, 36));
        sizePolicy1.setHeightForWidth(num_4_Bt->sizePolicy().hasHeightForWidth());
        num_4_Bt->setSizePolicy(sizePolicy1);
        t_Bt = new QPushButton(widget);
        t_Bt->setObjectName(QString::fromUtf8("t_Bt"));
        t_Bt->setGeometry(QRect(250, 101, 51, 36));
        sizePolicy1.setHeightForWidth(t_Bt->sizePolicy().hasHeightForWidth());
        t_Bt->setSizePolicy(sizePolicy1);
        f_Bt = new QPushButton(widget);
        f_Bt->setObjectName(QString::fromUtf8("f_Bt"));
        f_Bt->setGeometry(QRect(250, 146, 51, 36));
        sizePolicy1.setHeightForWidth(f_Bt->sizePolicy().hasHeightForWidth());
        f_Bt->setSizePolicy(sizePolicy1);
        m_Bt = new QPushButton(widget);
        m_Bt->setObjectName(QString::fromUtf8("m_Bt"));
        m_Bt->setGeometry(QRect(430, 191, 51, 36));
        sizePolicy1.setHeightForWidth(m_Bt->sizePolicy().hasHeightForWidth());
        m_Bt->setSizePolicy(sizePolicy1);
        i_Bt = new QPushButton(widget);
        i_Bt->setObjectName(QString::fromUtf8("i_Bt"));
        i_Bt->setGeometry(QRect(430, 101, 51, 36));
        sizePolicy1.setHeightForWidth(i_Bt->sizePolicy().hasHeightForWidth());
        i_Bt->setSizePolicy(sizePolicy1);
        zh_6_Bt = new QPushButton(widget);
        zh_6_Bt->setObjectName(QString::fromUtf8("zh_6_Bt"));
        zh_6_Bt->setGeometry(QRect(310, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_6_Bt->sizePolicy().hasHeightForWidth());
        zh_6_Bt->setSizePolicy(sizePolicy1);
        p_Bt = new QPushButton(widget);
        p_Bt->setObjectName(QString::fromUtf8("p_Bt"));
        p_Bt->setGeometry(QRect(550, 100, 51, 36));
        sizePolicy1.setHeightForWidth(p_Bt->sizePolicy().hasHeightForWidth());
        p_Bt->setSizePolicy(sizePolicy1);
        num_8_Bt = new QPushButton(widget);
        num_8_Bt->setObjectName(QString::fromUtf8("num_8_Bt"));
        num_8_Bt->setGeometry(QRect(670, 100, 51, 36));
        sizePolicy1.setHeightForWidth(num_8_Bt->sizePolicy().hasHeightForWidth());
        num_8_Bt->setSizePolicy(sizePolicy1);
        c_Bt = new QPushButton(widget);
        c_Bt->setObjectName(QString::fromUtf8("c_Bt"));
        c_Bt->setGeometry(QRect(190, 191, 51, 36));
        sizePolicy1.setHeightForWidth(c_Bt->sizePolicy().hasHeightForWidth());
        c_Bt->setSizePolicy(sizePolicy1);
        zh_4_Bt = new QPushButton(widget);
        zh_4_Bt->setObjectName(QString::fromUtf8("zh_4_Bt"));
        zh_4_Bt->setGeometry(QRect(190, 56, 51, 36));
        sizePolicy1.setHeightForWidth(zh_4_Bt->sizePolicy().hasHeightForWidth());
        zh_4_Bt->setSizePolicy(sizePolicy1);

        retranslateUi(KeyBoard);

        QMetaObject::connectSlotsByName(KeyBoard);
    } // setupUi

    void retranslateUi(QDialog *KeyBoard)
    {
        KeyBoard->setWindowTitle(QCoreApplication::translate("KeyBoard", "Dialog", nullptr));
        pushButton_shangjuhao->setText(QCoreApplication::translate("KeyBoard", "\302\260", nullptr));
        num_7_Bt->setText(QCoreApplication::translate("KeyBoard", "7", nullptr));
        a_Bt->setText(QCoreApplication::translate("KeyBoard", "a", nullptr));
        delBt->setText(QCoreApplication::translate("KeyBoard", "Del", nullptr));
        g_Bt->setText(QCoreApplication::translate("KeyBoard", "g", nullptr));
        pushButton_liangpie->setText(QCoreApplication::translate("KeyBoard", "\"", nullptr));
        x_Bt->setText(QCoreApplication::translate("KeyBoard", "x", nullptr));
        num_5_Bt->setText(QCoreApplication::translate("KeyBoard", "5", nullptr));
        k_Bt->setText(QCoreApplication::translate("KeyBoard", "k", nullptr));
        caps_Bt->setText(QCoreApplication::translate("KeyBoard", "Caps", nullptr));
        w_Bt->setText(QCoreApplication::translate("KeyBoard", "w", nullptr));
        prevBt->setText(QCoreApplication::translate("KeyBoard", "<", nullptr));
        spaceBt->setText(QCoreApplication::translate("KeyBoard", "space", nullptr));
        nextBt->setText(QCoreApplication::translate("KeyBoard", ">", nullptr));
        num_6_Bt->setText(QCoreApplication::translate("KeyBoard", "6", nullptr));
        o_Bt->setText(QCoreApplication::translate("KeyBoard", "o", nullptr));
        num_1_Bt->setText(QCoreApplication::translate("KeyBoard", "1", nullptr));
        zh_10_Bt->setText(QString());
        pushButton_danshu->setText(QCoreApplication::translate("KeyBoard", "-", nullptr));
        zh_us_Bt->setText(QCoreApplication::translate("KeyBoard", "\344\270\255/\350\213\261", nullptr));
        zh_3_Bt->setText(QString());
        q_Bt->setText(QCoreApplication::translate("KeyBoard", "q", nullptr));
        n_Bt->setText(QCoreApplication::translate("KeyBoard", "n", nullptr));
        y_Bt->setText(QCoreApplication::translate("KeyBoard", "y", nullptr));
        h_Bt->setText(QCoreApplication::translate("KeyBoard", "h", nullptr));
        langLb->setText(QCoreApplication::translate("KeyBoard", "\350\213\261\346\226\207", nullptr));
        d_Bt->setText(QCoreApplication::translate("KeyBoard", "d", nullptr));
        r_Bt->setText(QCoreApplication::translate("KeyBoard", "r", nullptr));
        num_0_Bt->setText(QCoreApplication::translate("KeyBoard", "0", nullptr));
        num_2_Bt->setText(QCoreApplication::translate("KeyBoard", "2", nullptr));
        u_Bt->setText(QCoreApplication::translate("KeyBoard", "u", nullptr));
        zh_7_Bt->setText(QString());
        zh_1_Bt->setText(QString());
        zh_9_Bt->setText(QString());
        s_Bt->setText(QCoreApplication::translate("KeyBoard", "s", nullptr));
        e_Bt->setText(QCoreApplication::translate("KeyBoard", "e", nullptr));
        j_Bt->setText(QCoreApplication::translate("KeyBoard", "j", nullptr));
        showLb->setText(QString());
        num_3_Bt->setText(QCoreApplication::translate("KeyBoard", "3", nullptr));
        b_Bt->setText(QCoreApplication::translate("KeyBoard", "b", nullptr));
        pushButton_pie->setText(QCoreApplication::translate("KeyBoard", "'", nullptr));
        z_Bt->setText(QCoreApplication::translate("KeyBoard", "z", nullptr));
        zh_5_Bt->setText(QString());
        v_Bt->setText(QCoreApplication::translate("KeyBoard", "v", nullptr));
        num_9_Bt->setText(QCoreApplication::translate("KeyBoard", "9", nullptr));
        l_Bt->setText(QCoreApplication::translate("KeyBoard", "l", nullptr));
        zh_8_Bt->setText(QString());
        zh_2_Bt->setText(QString());
        closeBt->setText(QCoreApplication::translate("KeyBoard", "\357\271\200", nullptr));
        num_4_Bt->setText(QCoreApplication::translate("KeyBoard", "4", nullptr));
        t_Bt->setText(QCoreApplication::translate("KeyBoard", "t", nullptr));
        f_Bt->setText(QCoreApplication::translate("KeyBoard", "f", nullptr));
        m_Bt->setText(QCoreApplication::translate("KeyBoard", "m", nullptr));
        i_Bt->setText(QCoreApplication::translate("KeyBoard", "i", nullptr));
        zh_6_Bt->setText(QString());
        p_Bt->setText(QCoreApplication::translate("KeyBoard", "p", nullptr));
        num_8_Bt->setText(QCoreApplication::translate("KeyBoard", "8", nullptr));
        c_Bt->setText(QCoreApplication::translate("KeyBoard", "c", nullptr));
        zh_4_Bt->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class KeyBoard: public Ui_KeyBoard {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_KEYBOARD_H
